### ISSUE TITLE
Remove Database Connection and use DBConnection.java in StatusNotes.java

### ISSUE THREAD

**Issue by ramtinnikbakht** [CST316FAF/cmsproject#45]
Remove Database Connection on line: 102-126 and instead use the DBConnection.java in StatusNotes.java whenever connecting to the database.

**Comment by eallam** [comment]
Iam going to fix it, and make sure.

**Comment by ramtinnikbakht** [comment]
Please don't touch it I am working on this issue.

Ramtin Nikbakht

**Comment by eallam** [comment]
Iam done to fix it.

Regards

Eallam

**Comment by eallam** [comment]
I started to work on it on Friday.

**Comment by ramtinnikbakht** [comment]
Please don't touch the issues I created man! 

Ramtin Nikbakht

**Comment by ramtinnikbakht** [comment]
Find your own issues in the project and fix them! Don't talk other members issues unless you ask for permission from them first to fix them. 

Ramtin Nikbakht

**Comment by eallam** [comment]
sorry

I do not want to bother you, but I talked to Dr.Gary and Austin. They told
me it does not matter if you work for your code or different code. Indeed,
I fixed different codes. Iam going to push it, but I fixed because I wanted
to help you as Dr.gary saying and Austin.Also, I asked Kunnal on Wednesday.

Accept my apology

Have a good one

Regards

Eallam

**Comment by ramtinnikbakht** [comment]
I am working on this issue and have been working on it so please do not work on the same issue as me. You can pick another issue, but do not pick the same one I am working on.

**Comment by ramtinnikbakht** [comment]
Resolved Issue. Git Commit #: 221f358e1345a16a580ad3c981018ad581012a2d
